### ISSUE TITLE
Mappings break if Starfinder Second Edition Playtest Deluxe Adventure Pack is installed.

### ISSUE THREAD

**Issue by jfn4th** [manuel-hegner/pf2e-all-tokens#3]
After installing Starfinder Second Edition Playtest Deluxe Adventure Pack and reloading a world to update mappings, mapped images no longer load for creatures. JSON mapping files appear to still be loading and images display if their associated module is active.

**Comment by manuel-hegner** [comment]
This should be fixed in v1.7

**Comment by roi007leaf** [comment]
Compendium mapper still broken for me after installing the 2 starfinder modules (playtest and adventures deluxe)
